### ISSUE TITLE
Make graphical visualization 

### ISSUE THREAD

**Issue by varunjain99** [Zeus-Labs/ZeusCloud#134]
Endpoint: /api/getRuleGraph with 2 parameters: (rule_id and the resource_id)
(e.g. http://localhost:80/api/getRuleGraph?resource_id=i-042e15a09ebb96776&rule_id=attackpath/private_vm_admin_permissions)

Consider the following structs:
```
type DisplayNode struct {
  // Label will tell the type of the node
  NodeLabel string `json:"node_label"`
  // resourceId uniquely identifyin the node
  ResourceId string `json:"resource_id"`
  // displayId to show in visualization
  DisplayId string `json:"display_id"`
}
```

```
type DisplayPath struct {
  DisplayPath []DisplayNodes `json:"display_path"`
}
```

```
type DisplayGraph struct {
  CentralNode DisplayNode `json:"central_node"`
  LeftSidePaths []DisplayPath `json:"left_side_paths"`
  RightSidePaths []DisplayPath `json:"right_side_paths"`
}
```

The API will return a `DisplayGraph` struct. 

The graph to be displayed revolves around a star model. You have the left side paths are the paths that are coming out of the central and forming a path to the left the central node. The RightSidePaths are coming out of the central node and forming a path to the right of the central node. LeftSidePaths and RightSidePaths include the CentralNode.

For each DisplayNode, the Label determines the icon and the color of the icon. We also show the Label and the DisplayId below the icon in the visualization. You should make a catalog of node label to node icon mappings. Initially, we care about the following node labels (ELBv2, Internet, EC2SecurityGroup, EC2Instance, IAMRole, IAMPolicy, IAMUser)

The resulting graph would a bit parabolic on the left and right sides. This way the delineation between right and left is more clear. The first path should be horizontal. Then each additional path you can draw a path on the upper or lower side. This way the graph is also balanced. Ideally the edges are colored - perhaps a gradient between the colors of the node they put together.

It’s possible that certain adjacent paths have overlapping sets of nodes. You should check if the existing node has been drawn. If so, use that existing node (in other words, don't duplicate a node with the same label and resource ID).

**Comment by vishjain** [comment]
Here are sample output from the api: 
{
   "central_node":{
      "node_label":"AWS Account",
      "resource_id":436,
      "display_id":"[aws account #]"
   },
   "left_side_paths":null,
   "right_side_paths":[
      {
         "display_nodes":[
            {
               "node_label":"AWS Account",
               "resource_id":436,
               "display_id":"[aws account #]"
            },
            {
               "node_label":"AWS Principal",
               "resource_id":435,
               "display_id":"arn:aws:iam::[aws account #]:root"
            },
            {
               "node_label":"AWS Role",
               "resource_id":434,
               "display_id":[rolearn]
            },
            {
               "node_label":"AWS Account",
               "resource_id":399,
               "display_id":"[aws account]"
            }
         ]
      }
   ]
}

**Comment by varunjain99** [comment]
completed
